properties([
    parameters([
        string(
            name: 'Environment',
            description: 'Select the environment to deploy',
            defaultValue: 'prod'
        ),
        choice(
            name: 'Terraform_Action',
            description: 'Select the Terraform action to perform',
            choices: ['plan', 'apply', 'destroy']
        )
    ])
])

pipeline {

    agent any

    stages {

        stage('Terraform Init') {

            steps {

                dir('eks-infra') {

                    sh 'terraform init'
                }
            }
        }


        stage('Terraform Validate') {

            steps {

                dir('eks-infra') {

                    sh 'terraform validate'
                }
            }
        }


        stage('Terraform Action') {

            steps {

                dir('eks-infra') {

                    withAWS(
                        credentials: 'aws-creds',
                        region: 'us-east-1'
                    ) {

                        script {

                            if (params.Terraform_Action == 'plan') {

                                sh """
                                    terraform plan \
                                    -var-file="${params.Environment}.tfvars"
                                """

                            } else if (params.Terraform_Action == 'apply') {

                                sh """
                                    terraform apply \
                                    -var-file="${params.Environment}.tfvars" \
                                    -auto-approve
                                """

                            } else if (params.Terraform_Action == 'destroy') {

                                sh """
                                    terraform destroy \
                                    -var-file="${params.Environment}.tfvars" \
                                    -auto-approve
                                """

                            } else {

                                error "Invalid Terraform action: ${params.Terraform_Action}"
                            }
                        }
                    }
                }
            }
        }
    }
}